library(shiny)

# Define UI for data upload app ----
ui <- fluidPage(
    
    # App title ----
    titlePanel("LongGold Codebook"),
    
    # Sidebar layout with flowLayout input and output definitions ----
    sidebarLayout(
        sidebarPanel(
                        # Input: Select information ----
            checkboxGroupInput("info", "Information",
                         choices = c("Brief Information" = "info",
                                     "Number of items" = "number_items",
                                     "Response format" = "response_format",
                                     "Link to online version" = "link_online_version",
                                     "Link to paper" = "link_publication",
                                     "Reliability Alpha" = "rel_cronbach_alpha",
                                     "Reliability Omega" = "rel_macdonald_omega",
                                     "Reliabilty Retest" = "rel_test_retest",
                                     "SEM" = "sem",
                                     "Guessing Probability" = "threshold_guess_prob",
                                     "Reference" = "reference",
                                     "Additional reference" = "reference_2",
                                     "Mean from original study" = "mean",
                                     "SD from original study" = "sd"
                                     ),
                         selected = "info"),
            checkboxGroupInput("language", "Language selection",
                               choices = c("English" = "english",
                                           "German" = "german"),
                               selected = "english"),
            width = 2
        ),

        # Main panel for displaying outputs ----
        mainPanel(
            tabsetPanel(type = "tabs",
                        tabPanel("Introduction", htmlOutput("introduction")),
                        tabPanel("Select Self-report Scales", 
                                 inputPanel(
                                     # Input: Select scale ----
                                     checkboxGroupInput("scales", "Select Self-report Scales",
                                                        choices = c("Concurrent Musical Activities (CCM)" = "ccm",
                                                                    "Drama Activity (DAC)" = "dac",
                                                                    "Demographics (DEG)" = "deg",
                                                                    "Goldsmiths Musical Sophistication Index (GMS)" = "gms",
                                                                    "Social Desirability (Lie) Scale (LIE)" = "lie",
                                                                    "Musical Home Environment (MHE)" = "mhe",
                                                                    "Physical Activity Questionnaire for Older Children (PAC)" = "pac",
                                                                    "Academic Self Concept (SCA)" = "sca",
                                                                    "Social Self Concept (SCS)" = "scs",
                                                                    "Strengths and Difficulties Questionnaire (SDQ)" = "sdq",
                                                                    "School Engagement Measurement (SEM)" = "sem",
                                                                    "Socio-economic Status (SES)" = "ses",
                                                                    "Student Opinion Scale (SOS)" = "sos",
                                                                    "Theory of Intelligence (TOI)" = "toi",
                                                                    "Theory of Musicality (TOM)" = "tom",
                                                                    "Ten Item Personality Inventory (TIP)" = "tip"
                                                        ),
                                                        selected = "gms")
                                 )),
                        tabPanel("Select Performance Tests", inputPanel(
                            # Input: Select tests ----
                            selectInput("bat", "Beat Perception Test (BAT)",
                                               choices = c("Not selected" = "",
                                                           "Default" = "default",
                                                           "24" = "24",
                                                           "23" = "23",
                                                           "22" = "22",
                                                           "21" = "21",
                                                           "20" = "20",
                                                           "19" = "19",
                                                           "18" = "18",
                                                           "17" = "17",
                                                           "16" = "16",
                                                           "15" = "15"
                                                           ),
                                               selected = ""),
                            selectInput("edt", "Emotion Discrimination Test (EDT)",
                                        choices = c("Not selected" = "",
                                                    "Default" = "default",
                                                    "17" = "17",
                                                    "16" = "16",
                                                    "15" = "15"
                                                    ),
                                        selected = ""),
                            selectInput("jaj", "Jack and Jill Working Memory Test (JAJ)",
                                        choices = c("Not selected" = "",
                                                    "Default" = "default"
                                                    ),
                                        selected = ""),
                            selectInput("mdt", "Melody Discrimination Test (MDT)",
                                        choices = c("Not selected" = "",
                                                    "Default" = "default",
                                                    "19" = "19",
                                                    "18" = "18",
                                                    "17" = "17",
                                                    "16" = "16",
                                                    "15" = "15",
                                                    "14" = "14",
                                                    "13" = "13",
                                                    "12" = "12"),
                                        selected = ""),
                            selectInput("miq", "Matrix reasoning IQ Test (MIQ)",
                                        choices = c("Not selected" = "",
                                                    "Default" = "default",
                                                    "11" = "11",
                                                    "10" = "10",
                                                    "9" = "9",
                                                    "8" = "8",
                                                    "7" = "7",
                                                    "6" = "6",
                                                    "5" = "5",
                                                    "4" = "4"),
                                        selected = ""),
                            selectInput("mps", "Musical Preference Assessment (MPS)",
                                        choices = c("Not selected" = "",
                                                    "Default" = "default"),
                                        selected = ""),
                            selectInput("mpt", "Mistuning Perception Test (MPT)",
                                        choices = c("Not selected" = "",
                                                    "Default" = "default",
                                                    "21" = "21",
                                                    "20" = "20",
                                                    "19" = "19",
                                                    "18" = "18",
                                                    "17" = "17",
                                                    "16" = "16",
                                                    "15" = "15"),
                                        selected = ""),
                            selectInput("rat", "Rhythm Ability Test (RAT)",
                                        choices = c("Not selected" = "",
                                                    "Default" = "default",
                                                    "19" = "19",
                                                    "18" = "18",
                                                    "17" = "17",
                                                    "16" = "16",
                                                    "15" = "15",
                                                    "14" = "14",
                                                    "13" = "13",
                                                    "12" = "12",
                                                    "11" = "11",
                                                    "10" = "10",
                                                    "9" = "9",
                                                    "8" = "8"),
                                        selected = ""),
                            selectInput("sss", "Sound Similiarity Sorting Test (SSS)",
                                        choices = c("Not selected" = "",
                                                    "Default" = "default"),
                                        selected = ""),
                            selectInput("pit", "Pitch Imagery Arrows Test (PIT)",
                                        choices = c("Not selected" = "",
                                                    "35" = "35",
                                                    "34" = "34",
                                                    "33" = "33",
                                                    "32" = "32",
                                                    "31" = "31",
                                                    "Default" = "default",
                                                    "29" = "29",
                                                    "28" = "28",
                                                    "27" = "27",
                                                    "26" = "26",
                                                    "25" = "25",
                                                    "24" = "24",
                                                    "23" = "23",
                                                    "22" = "22",
                                                    "21" = "21",
                                                    "20" = "20",
                                                    "19" = "19",
                                                    "18" = "18",
                                                    "17" = "17",
                                                    "16" = "16"),
                                        selected = ""),
                            selectInput("bds", "Backward Digit Span Working Memory Test (BDS)",
                                        choices = c("Not selected" = "",
                                                    "Default" = "default"),
                                        selected = "")
                        )),
                        tabPanel("Output", 
                                 uiOutput("CB_custom"),
                                 tableOutput("outscale"),
                                 tableOutput("outtest")
                                 ),
                        tabPanel("Glossary", 
                                 htmlOutput("glossary")
                                 )
                        
            )
        )
        
    )
)